<?php

/*
 * This file is part of the Panda Ui Package.
 *
 * (c) Ioannis Papikas <papikas.ioan@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Panda\Ui\Html;

use DOMNodeList;
use Exception;
use InvalidArgumentException;
use Panda\Ui\Dom\DOMPrototype;
use Panda\Ui\Dom\Factories\DOMFactoryInterface;
use Panda\Ui\Dom\Handlers\DOMHandlerInterface;
use Panda\Ui\Html\Factories\HTMLFactoryInterface;
use Panda\Ui\Html\Handlers\HTMLHandlerInterface;
use Panda\Ui\Html\Helpers\HTMLHelper;

/**
 * Class HTMLDocument
 *
 * Magic methods:
 *
 * @method div($value = '', $id = '', $class = '');
 * @method p($value = '', $id = '', $class = '');
 *
 * @package Panda\Ui\Html
 */
class HTMLDocument extends DOMPrototype
{
    /**
     * Create a new DOM Document.
     *
     * @param HTMLHandlerInterface $HTMLHandler
     * @param HTMLFactoryInterface $HTMLFactory
     * @param string               $version
     * @param string               $encoding
     */
    public function __construct(HTMLHandlerInterface $HTMLHandler, HTMLFactoryInterface $HTMLFactory, $version = '1.0', $encoding = 'UTF_8')
    {
        // Construct DOMDocument
        parent::__construct($HTMLHandler, $HTMLFactory, $version, $encoding);
    }

    /**
     * Creates and returns a DOMElement with the specified tagName and the given attributes
     *
     * @param string $name  The tag of the element.
     * @param mixed  $value The content of the element. It can be a string or a DOMElement.
     * @param string $id    The id attribute
     * @param string $class The class attribute
     *
     * @return HTMLElement
     * @throws Exception
     */
    public function create($name = 'div', $value = '', $id = '', $class = '')
    {
        // Create a new HTMLElement
        return $this->getHTMLFactory()->buildHtmlElement($name, $value, $id, $class);
    }

    /**
     * Magic method to create all html tags automatically.
     *
     * @param string $name      The function name caught.
     *                          In this function it serves as the tag name.
     * @param array  $arguments All function arguments.
     *                          They serve as the content, id and class, like DOM::create().
     *
     * @return mixed
     * @throws Exception
     */
    public function __call($name, $arguments)
    {
        // Get method name and check for a valid html tag
        $name = strtolower($name);
        if (!HTMLHelper::validHtmlTag($name)) {
            throw new InvalidArgumentException(__METHOD__ . ': The given tag name is invalid.');
        }

        // Get rest of attributes
        $value = (count($arguments) > 0 ? $arguments[0] : '');
        $id = (count($arguments) > 1 ? $arguments[1] : '');
        $class = (count($arguments) > 2 ? $arguments[2] : '');

        // Create element
        return $this->create($name, $value, $id, $class);
    }

    /**
     * Selects nodes in the html document that match a given css selector.
     *
     * @param string $selector The css selector to search for in the html document.
     *                         It does not support pseudo-* for the moment and only supports simple equality
     *                         attribute-wise. Can hold multiple selectors separated with comma.
     * @param mixed  $context  Can either be a DOMElement as the context of the search, or a css selector.
     *                         If the selector results in multiple DOMNodes, then the first is selected as the context.
     *                         It is NULL by default.
     *
     * @return DOMNodeList|false
     * @throws InvalidArgumentException
     */
    public function select($selector, $context = null)
    {
        return $this->getHTMLHandler()->select($this, $selector, $context);
    }

    /**
     * Returns the HTML form of the document.
     *
     * @param bool $format Indicates whether to format the output.
     *
     * @return string The html generated by this document.,
     */
    public function getHTML($format = false)
    {
        $this->formatOutput = $format;

        return $this->saveHTML();
    }

    /**
     * @return HTMLHandlerInterface|DOMHandlerInterface
     */
    public function getHTMLHandler()
    {
        return $this->getDOMHandler();
    }

    /**
     * @return HTMLFactoryInterface|DOMFactoryInterface
     */
    public function getHTMLFactory()
    {
        return $this->getDOMFactory();
    }

    /**
     * @param HTMLFactoryInterface $HTMLFactory
     *
     * @return $this
     */
    public function setHTMLFactory($HTMLFactory)
    {
        return $this->setDOMFactory($HTMLFactory);
    }
}
